spring:
  datasource:
    url: jdbc:postgresql://<host>:5432/<database>
    username: <user>
    password: <pswd>
  jpa:
    generate-ddl: true
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
  kafka:
    consumer:
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="pswd";
    producer:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
      bootstrap-servers: <servers>
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

auto.create.topics.enable: true

server.port: 9191

order.topic.name: <topic>