server:
  port: 9091

spring:
  kafka:
    bootstrap-servers: sulky-01.srvs.cloudkafka.com:9094,sulky-02.srvs.cloudkafka.com:9094,sulky-03.srvs.cloudkafka.com:9094;
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaasl.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="<user>" password="<password>";
    consumer:
      group-id: <id>
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: sample.kafka
  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
      function:
        definition: orderPurchaseEventPublisher;transactionEventProcessor;
      bindings:
        orderPurchaseEventPublisher-out-0:
          destination: ni14yn7m-order
        transactionEventProcessor-in-0:
          destination: ni14yn7m-transactions
  datasource:
    url: jdbc:postgresql://<host>:5432/<database>
    driver-class-name: org.postgresql.Driver
    username: <user>
    password: <password>
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      show-sql: true
      ddl-auto: update
    generate-ddl: true