server:
  port: 9092

spring:
  kafka:
    bootstrap-servers: <servers>
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaasl.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="pswd";
    consumer:
      group-id: <group-id>
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: sample.kafka
  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
      function:
        definition: orderPurchaseEventPublisher;transactionEventProcessor;
      bindings:
        orderPurchaseEventPublisher-out-0:
          destination: <topic>
        transactionEventProcessor-in-0:
          destination: <topic>
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true